# Generated by Django 4.2.2 on 2023-06-17 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0002_rename_sensor_id_measurement_sensor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sensor',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='temp',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='time',
        ),
        migrations.AddField(
            model_name='measurement',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='measurement',
            name='temperature',
            field=models.DecimalField(decimal_places=1, default=True, max_digits=4),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
